Show free and other users issues
salmiakki/prpr pull request #57
Opened 2022-05-24 15:24 UTC by nikulin

2022-05-24 15:38 UTC, Roxe322 requested changes

2022-05-24 15:38 UTC, Roxe322 commented on README.md
> +                        show issues assigned for USER
Неочевидно, в каком формате передается USER - емейл ревьюера/имя?

2022-05-24 15:38 UTC, Roxe322 commented on prpr/main.py
> +    user = args.user or None
нельзя ли в арге определить default и не делать тут or?

2022-05-24 15:38 UTC, Roxe322 commented on prpr/startrack_client.py
> +    def _get_filter_expression(self, user: str = None):
Тайпинг неверный. Либо Optional[str] либо str | None, хз какой тут версии питон)

2022-05-24 15:38 UTC, Roxe322 commented on prpr/startrack_client.py
> +    def get_issues(self, user: str = None):
И тут

2022-05-24 15:56 UTC, nikulin commented on prpr/main.py
> +    user = args.user or None
fixed

2022-05-25 09:30 UTC, nikulin commented
> Setting both `--user` and `--free` should yield a warning (which of them is ignored) if not an exception.
added warning and change docs (--free overrides -u/--user).

2022-05-28 17:08 UTC, Roxe322 approved these changes

2022-06-13 17:46 UTC, merged